#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

security:
  users:
    limited:
      password: good
      roles: ADD
    full:
      password: good
      roles: [ADD, MINUS]
web:
  security:
    urls:
      -
        pattern: '/ws/**'
        filters: authcBasic
webServices:
  endpoints:
    CalculatorWS:
      implementation: org.seedstack.ws.fixtures.CalculatorServiceImpl
      wsdl: META-INF/ws/Calculator.wsdl
      url: /ws/calculator
      enableMtom: true
