#
# Copyright (c) 2013-2016, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

security:
  users:
    limited:
      password: good
      roles: ADD
    full:
      password: good
      roles: [ADD, MINUS]
jms:
  connectionFactories:
    myConnectionFactory:
      vendorClass: org.apache.activemq.ActiveMQConnectionFactory
      vendorProperties:
        brokerURL: vm://localhost?broker.persistent=false
  connections:
    myConnection:
      connectionFactory: myConnectionFactory
webServices:
  endpoints:
    CalculatorWS0:
      implementation: org.seedstack.ws.fixtures.CalculatorServiceImpl
      wsdl: META-INF/ws/Calculator.wsdl
      url: http://localhost:${sys.seed\.ws\.port}/ws/calculator
      enableMtom: true
    CalculatorWS1:
      implementation: org.seedstack.ws.fixtures.CalculatorServiceImpl
      wsdl: META-INF/ws/Calculator.wsdl
      binding: http://www.w3.org/2010/soapjms/
      url: jms:jndi:dynamicQueues/TEST.QUEUE?jndiInitialContextFactory=org.apache.activemq.jndi.ActiveMQInitialContextFactory&jndiConnectionFactoryName=ConnectionFactory&jndiURL=vm://localhost?broker.persistent=false
      enableMtom: true
    CalculatorWS2:
      implementation: org.seedstack.ws.fixtures.CalculatorServiceImpl
      wsdl: META-INF/ws/Calculator.wsdl
      binding: http://www.w3.org/2010/soapjms/
      url: jms:jndi:dynamicTopics/TEST.TOPIC?jndiInitialContextFactory=org.apache.activemq.jndi.ActiveMQInitialContextFactory&jndiConnectionFactoryName=ConnectionFactory&jndiURL=vm://localhost?broker.persistent=false
      enableMtom: true
