#
# Copyright © 2013-2020, The SeedStack authors <http://seedstack.org>
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
#

security:
  users:
    limited:
      password: good
      roles: ADD
    full:
      password: good
      roles: [ADD, MINUS]
webServices:
  endpoints:
    CalculatorWS1:
      implementation: org.seedstack.ws.fixtures.CalculatorCertificateImpl
      wsdl: META-INF/ws/wsdl/Calculator.wsdl
      url: http://localhost:${sys.seed\.ws\.port}/ws/calculator-certificate
      enableMtom: true
    CalculatorWS2:
      implementation: org.seedstack.ws.fixtures.CalculatorUsernameTokenImpl
      wsdl: META-INF/ws/wsdl/Calculator.wsdl
      url: http://localhost:${sys.seed\.ws\.port}/ws/calculator-username-token
      enableMtom: true
